INFO 2021-01-19 04:24:23,529 root : Сервер доступний. Час на сервері: 2021-01-19T02:24:23.527561
INFO 2021-01-19 04:24:23,529 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2021-01-19 04:24:23,529 root : Відповідь сервера місти наступні поля:
INFO 2021-01-19 04:24:23,529 root : Ключ: servername, Значення: lab server
INFO 2021-01-19 04:24:23,529 root : Ключ: random, Значення: 4
INFO 2021-01-19 04:24:23,529 root : Ключ: datetime, Значення: 2021-01-19T02:24:23.527561
INFO 2021-01-19 04:24:23,529 root : Ключ: server_url, Значення: http://localhost:8000/health/
INFO 2021-01-19 04:24:23,529 root : Ключ: server_iinfo, Значення: {'system': 'posix', 'srv_pid': 4002}
INFO 2021-01-19 04:24:23,529 root : Ключ: client_info, Значення: {'user agent': 'python-requests/2.22.0', 'remote addr': '127.0.0.1', 'remote host': ''}
ERROR 2021-01-19 04:25:23,532 root : Unable to conect to the server: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9e11d0b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
